### ISSUE TITLE
Asking

### ISSUE THREAD

**Issue by jhunzkie1991** [kaozaza2/openvpn-core#1]
How to chance this in openvpn

**Comment by kaozaza2** [comment]
Just a dumped code from openvpn connect, you can use as api for build your private openvpn app ☺️

**Comment by jhunzkie1991** [comment]
can i ask for a guide?
Please

**Comment by kaozaza2** [comment]
If you have a guide, you can use `jadx` for view java source  from `openvpn connect`

**Comment by kaozaza2** [comment]
Closed due no inactivity.
